Repository 2024-Summer-Bootcamp-TeamJ/Frontend, pull requests merged in 2024-07, with the labels that each got.

#5 [Design/#1] 멘토 선택 페이지 퍼블리싱
  .DS_Store
  node_modules/.vite/deps/_metadata.json
  node_modules/.yarn-integrity
  node_modules/path-scurry/node_modules/lru-cache/package.json
  src/App.tsx
  src/assets/images/BackgroundMentorPage.svg
  src/assets/images/ChoosingButtonBaek.svg
  src/assets/images/ChoosingButtonOh.svg
  src/assets/images/ChoosingButtonShin.svg
  src/assets/images/IconToMyPage.svg
  src/assets/images/ProfileBackBaek.svg
  src/assets/images/ProfileBackOh.svg
  src/assets/images/ProfileBackShin.svg
  src/assets/images/ProfileFrontBaek.svg
  src/assets/images/ProfileFrontOh.svg
  src/assets/images/ProfileFrontShin.svg
  src/index.css
  src/pages/MentorPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#10 [Design/#6] 마이페이지 퍼블리싱
  .gitignore
  src/App.tsx
  src/assets/fonts/MoonFlower.ttf
  src/assets/fonts/NoticiaText.ttf
  src/assets/images/AllLetter.svg
  src/assets/images/IconLetter.svg
  src/assets/images/IconMouse.svg
  src/assets/images/IconToHome.svg
  src/assets/images/MyPageBackground.svg
  src/assets/images/PostBox.svg
  src/assets/images/fromBaek.svg
  src/assets/images/fromOh.svg
  src/assets/images/fromShin.svg
  src/assets/images/redButtonAll.svg
  src/assets/images/redButtonBaek.svg
  src/assets/images/redButtonOh.svg
  src/assets/images/redButtonShin.svg
  src/index.css
  src/pages/MentorPage.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: 🎨Design

#11 [Design/#8]: 처방전 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/prescription.svg
  src/components/PostText/HightlightText.tsx
  src/components/PostText/ImageWithText.tsx
  src/pages/PrescriptionPage.tsx
Labels: 🎨Design

#13 [Design/#12] 멘토 선택 페이지 애니메이션 추가
  .DS_Store
  src/App.tsx
  src/assets/images/ChoosingButtonBaek.svg
  src/assets/images/ChoosingButtonOh.svg
  src/assets/images/ChoosingButtonShin.svg
  src/index.css
  src/pages/MentorPage.tsx
  src/pages/PrescriptionPage.tsx
  tailwind.config.js
Labels: 🎨Design

#15 [refactor/#14] 주스탄드 설정
  package.json
  src/App.tsx
  store.ts
  yarn.lock
Labels: 🔨Refactor

#16 [design/#14] 프로필 이미지 수정
  src/assets/images/ProfileFrontBaek.svg
  src/assets/images/ProfileFrontShin.svg
Labels: 🎨Design

#20 [Design/#3] 채팅 페이지 구현
  .DS_Store
  .gitignore
  src/.DS_Store
  src/App.css
  src/App.tsx
  src/ThemeContext.tsx
  src/assets/images/Baek.svg
  src/assets/images/backgroundBaek.svg
  src/assets/images/backgroundOh.svg
  src/assets/images/backgroundShin.svg
  src/assets/images/chatbubble.png
  src/assets/images/oh.svg
  src/assets/images/shin.svg
  src/components/ChatBubble/CharacterImage.tsx
  src/components/ChatBubble/ChatMessage.tsx
  src/components/ChatBubble/MentorName.tsx
  src/components/MentorChatBubble/CharacterImage.tsx
  src/components/MentorChatBubble/ChatBubble.tsx
  src/components/MentorChatBubble/ChatMessage.tsx
  src/components/MentorChatBubble/MentorName.tsx
  src/components/MyChatBubble/MyChatBubble.tsx
  src/components/MyChatBubble/MyChatMessage.tsx
  src/components/MyChatBubble/MyName.tsx
  src/components/chat/ChatContainer.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/MentorChatBubble.tsx
  src/components/chat/MyChatBubble.tsx
  src/index.css
  src/main.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/theme.ts
  yarn.lock
Labels: 🎨Design

#27 [design/#26] 채팅 페이지 수정 (+라우팅 설정 및 대화 종료 버튼 추가)
  package.json
  src/App.tsx
  src/assets/fonts/syndinaroo.ttf
  src/components/FirstPage/Button.tsx
  src/components/chat/ChatContainer.tsx
  src/components/chat/MentorChatBubble.tsx
  src/components/chat/MyChatBubble.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: 🎨Design

#32 [Feat]: 첫 페이지 새로운 유저 생성
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/StartButton.tsx
  src/pages/FirstPage.tsx
Labels: ✨Feat

#33 [Feat/#29] 채팅방 생성, 삭제 및 처방전 생성 api 연동
  src/App.tsx
  src/components/FirstPage/Button.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/MentorPage.tsx
  vite.config.ts
Labels: ✨Feat

#35 [Feat/#30] 처방전, 마이페이지 api 연동
  src/App.tsx
  src/assets/images/prescriptionimg.svg
  src/components/PostText/ImageWithText.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
  store.ts
Labels: ✨Feat

#37 [Feat/#36] 마이페이지 userId 받기
  src/App.tsx
  src/components/FirstPage/StartButton.tsx
  src/components/PostText/ImageWithText.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/pages/MyPage.tsx
  store.ts
Labels: ✨Feat

#39 [feat] 채팅창 멘토 아이디 연동 수정
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/StartButton.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/pages/MyPage.tsx
Labels: ✨Feat

#44 [Design/#38] 디자인 수정
  src/pages/FirstPage.tsx
  store.ts
Labels: 🎨Design

#46 [design/#45] 멘토 페이지 애니메이션
  .DS_Store
  src/assets/images/CardBaek.svg
  src/assets/images/CardOh.svg
  src/assets/images/CardShin.svg
  src/assets/images/CharBaek.svg
  src/assets/images/CharOh.svg
  src/assets/images/CharShin.svg
  src/index.css
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/store/store.ts
  store.ts
Labels: 🎨Design

#47 Design : 시작 페이지 디자인과 배경음악 설정
  index.html
  package.json
  src/assets/images/Racoon.svg
  src/assets/images/RectIntro.svg
  src/assets/images/backgroundBeach.svg
  src/assets/images/backgroundForest.svg
  src/assets/images/eveningSky.svg
  src/assets/images/scrollMessage.svg
  src/assets/images/welcomeBackground.svg
  src/assets/images/welcomeLogo.svg
  src/assets/images/yellowDog.svg
  src/assets/music/backgroundMusic.mp3
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/CharIntro1.css
  src/components/FirstPage/CharIntro1.tsx
  src/components/FirstPage/CharIntro2.css
  src/components/FirstPage/CharIntro2.tsx
  src/components/FirstPage/EveningSky.css
  src/components/FirstPage/EveningSky.tsx
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/LoginPage.tsx
  src/components/FirstPage/StartButton.tsx
  src/components/FirstPage/WelcomePage.css
  src/components/FirstPage/WelcomePage.tsx
  src/pages/FirstPage.tsx
  src/pages/MyPage.tsx
  yarn.lock
Labels: 🎨Design

#48 [Feat/#43] 웹소켓 연동 및 디자인 수정
  src/assets/images/mail.svg
  src/assets/images/mailback.svg
  src/assets/images/mailfront.svg
  src/components/chat/ChatContainer.tsx
  src/components/chat/ChatInput.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/PrescriptionPage.tsx
  src/store/store.ts
  tsconfig.json
Labels: ✨Feat

#50 [Design/#45] 효과음, 애니메이션
  package.json
  src/assets/audios/PostOffice.mp3
  src/assets/audios/button.mp3
  src/assets/audios/button_pressed.mp3
  src/assets/audios/choose.mp3
  src/assets/audios/click_effect.mp3
  src/assets/audios/flipcard.mp3
  src/assets/audios/mouse.mp3
  src/assets/audios/prescriptionPageAudio.mp3
  src/assets/audios/toy_button.mp3
  src/assets/audios/ui_click.mp3
  src/components/chat/ChatContainer.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/MentorPage.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#52 [feat/#49] 처방전 생성 오류 수정
  src/components/FirstPage/StartButton.tsx
  src/components/PostText/ImageWithText.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/pages/PrescriptionPage.tsx
  src/store/store.ts
Labels: ✨Feat

#55 [Design/#51] 알림창 디자인과 FirstPage 변경
  package-lock.json
  package.json
  src/components/FirstPage/LoginPage.tsx
  src/components/FirstPage/StartButton.tsx
  src/components/chat/ChatContainer.tsx
  src/pages/FirstPage.tsx
  yarn.lock
Labels: 🎨Design

#60 [fix/#59] 머지 오류 수정
  src/components/chat/ChatContainer.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/FirstPage.tsx
Labels: ❤️‍🔥BugFix

#65 [design/#61] 마이페이지 모바일 버전
  src/App.tsx
  src/pages/Mobile_MyPage.tsx
Labels: 🎨Design

#67 [fix/#62] api 오류 수정 및 디자인 수정
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/LoginPage.tsx
  src/components/chat/ChatContainer.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
Labels: ❤️‍🔥BugFix

#72 [feat/#69] .env 파일 url 경로 수정
  .env
  .env.development
  .env.local
  .env.production
  .env.test
  package.json
  src/components/FirstPage/LoginPage.tsx
  src/components/PostText/ImageWithText.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/pages/Mobile_MyPage.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
  vite.config.ts
  yarn.lock
Labels: ✨Feat

#75 [fix/#73] 빌드 파일 오류 수정 - 이미지 경로 변경
  dist/assets/Baek-CA0vsuuO.svg
  dist/assets/CardBaek-BJrln2wY.svg
  dist/assets/CharBaek-Cg0nREUE.svg
  dist/assets/CharOh-CNN9660u.svg
  dist/assets/CharShin-CitbRfsY.svg
  dist/assets/ChoosingButtonBaek-BoIvCu7z.svg
  dist/assets/ChoosingButtonOh-D6ehiBxf.svg
  dist/assets/IconLetter-BS0FaJxp.svg
  dist/assets/IconMouse-CK56bKLj.svg
  dist/assets/IconToHome-19ZuwmtR.svg
  dist/assets/MoonFlower-BpPDa5mm.ttf
  dist/assets/MyPageBackground-BLE9f90t.svg
  dist/assets/NoticiaText-Dxyt17E8.ttf
  dist/assets/PostBox-DklS2GuD.svg
  dist/assets/PostOffice-B9Fm3m3d.mp3
  dist/assets/ProfileBackBaek-BuvH7K03.svg
  dist/assets/ProfileBackOh-BoHRorNm.svg
  dist/assets/ProfileBackShin-CXwpWun3.svg
  dist/assets/backgroundBaek-DmmqKhQS.svg
  dist/assets/backgroundGreen-D8LJII2_.svg
  dist/assets/backgroundOh-CeZa6xlE.svg
  dist/assets/backgroundShin-CIJE5vkL.svg
  dist/assets/chatbubble-DYku0HZm.png
  dist/assets/choose-UyHchCCZ.mp3
  dist/assets/click_effect-CrkPjc3w.mp3
  dist/assets/flipcard-C-SIaE8h.mp3
  dist/assets/fromBaek-ntyuIl1J.svg
  dist/assets/fromOh-CNt-LUsg.svg
  dist/assets/fromShin-_CSFHRvK.svg
  dist/assets/groupLogo-D4hWmRPa.svg
  dist/assets/index-BVLCWQx_.js
  dist/assets/index-CrLOuFRP.css
  dist/assets/mobile_prescriptionimg-BQcynKzr.svg
  dist/assets/mouse-DWajUTj1.mp3
  dist/assets/oh-BvDb_Onh.svg
  dist/assets/prescriptionimg-GzsKk_fA.svg
  dist/assets/redButtonBaek-BEkLscae.svg
  dist/assets/redButtonOh-CPQK7HBO.svg
  dist/assets/redButtonShin-DwowYCbT.svg
  dist/assets/shin-DazsqA6f.svg
  dist/assets/syndinaroo-Bs3PV56G.ttf
  dist/index.html
  src/components/FirstPage/LoginPage.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
Labels: ❤️‍🔥BugFix

#79 [Design/#78] 마이페이지, 처방전 페이지, 채팅 페이지 반응형 퍼블리싱
  src/assets/images/mobile_prescriptionimg.svg
  src/components/chat/ChatContainer.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
  tailwind.config.js
Labels: 🎨Design

#77 [Design/#68] 시작 페이지, 멘토 페이지 반응형 디자인(모바일) 적용
  package.json
  src/assets/images/leaf.svg
  src/assets/images/leftArrow.svg
  src/assets/images/rightArrow.svg
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/CharIntro1.tsx
  src/components/FirstPage/CharIntro2.tsx
  src/components/FirstPage/EveningSky.tsx
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/LoginPage.tsx
  src/components/FirstPage/WelcomePage.tsx
  src/components/chat/ChatContainer.tsx
  src/index.css
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#82 [fix/#81] 배포 전 오류수정
  src/components/chat/ChatContainer.tsx
Labels: ❤️‍🔥BugFix

#85 [Design/#83] 효과음, 채팅 페이지 반응형
  src/assets/images/baek_mentorChatBubble.svg
  src/assets/images/oh_mentorChatBubble.svg
  src/assets/images/shin_mentorChatBubble.svg
  src/components/chat/ChatContainer.tsx
  src/components/chat/MentorChatBubble.tsx
  src/components/chat/MyChatBubble.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
Labels: 🎨Design

#86 [Design/#84] : 시작페이지 디자인 보충
  src/assets/audios/mainMusic.mp3
  src/assets/music/backgroundMusic.mp3
  src/components/FirstPage/Input.tsx
  src/components/FirstPage/LoginPage.css
  src/components/FirstPage/LoginPage.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
Labels: 🎨Design

#89 [fix/#87] 처방전 생성 후 아이디 수정
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
Labels: ❤️‍🔥BugFix

#98 [chore/#97] 깃허브액션 파일 추가
  .github/workflows/deploy.yml
Labels: 🌎Deploy

#99 [chore/#97] 깃허브액션 파일 수정
  .github/workflows/deploy.yml
Labels: 🌎Deploy

#100 [chore] 깃허브액션 파일 2차 수정
  .github/workflows/deploy.yml
Labels: 🌎Deploy

#101 [Chore/#97] 깃허브 액션 파일 4차 수정
  .github/workflows/deploy.yml
Labels: 🌎Deploy

#102 [chore] 깃허브액션 파일 5차 수정
  .github/workflows/deploy.yml
Labels: 🌎Deploy

#94 [Feat/#91] : 채팅 페이지 문장 나누기
  src/components/chat/ChatContainer.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
Labels: ✨Feat

#107 [deploy/#105] 배포 오류 수정
  .env.development
  .env.local
  .env.production
  .env.test
  dist/assets/index-BP9I4JBo.js
  dist/assets/index-kRV1aGTp.js
  dist/index.html
  src/components/FirstPage/LoginPage.tsx
  src/components/PostText/ImageWithText.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/FirstPage.tsx
  src/pages/MentorPage.tsx
  src/pages/Mobile_MyPage.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
  vite.config.ts
Labels: 🌎Deploy

#110 [fix/#109] 처방전 오류 수정 - 폴링
  src/components/PostText/ImageWithText.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/PrescriptionPage.tsx
  src/store/store.ts
Labels: ❤️‍🔥BugFix

#113 [Design/#108] 채팅페이지 반응형, 말풍선 수정
  src/components/FirstPage/Button.tsx
  src/components/chat/ChatContainer.tsx
  src/components/chat/MentorChatBubble.tsx
  src/components/chat/MyChatBubble.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  tailwind.config.js
Labels: 🎨Design

#112 [Feat/#111] : 로그인 페이지 Throttling, Debouncing 적용
  package.json
  src/components/FirstPage/LoginPage.tsx
  yarn.lock
Labels: ✨Feat

#121 [Feat/#120] 채팅페이지 scrollToBottom 작동
  dist/assets/Baek-COCTo-04.svg
  dist/assets/CardBaek-DrBdoS2g.svg
  dist/assets/CharBaek-HZRdnelM.svg
  dist/assets/CharOh-CEkf53wz.svg
  dist/assets/CharShin-BPbn4s-a.svg
  dist/assets/ChoosingButtonBaek-CjLdFOGc.svg
  dist/assets/ChoosingButtonOh-CAJzv0hE.svg
  dist/assets/IconLetter-Bf5kXeAo.svg
  dist/assets/IconMouse-Den-z3Fg.svg
  dist/assets/IconToHome-BBGs1vYo.svg
  dist/assets/MyPageBackground-DekmgsB7.svg
  dist/assets/PostBox-DZ6XiAZk.svg
  dist/assets/ProfileBackBaek-BDgtaFl5.svg
  dist/assets/ProfileBackOh-DHArOrGF.svg
  dist/assets/ProfileBackShin-UicqqSC4.svg
  dist/assets/backgroundBaek-BpeExazP.svg
  dist/assets/backgroundGreen-Bnbts40_.svg
  dist/assets/backgroundOh-1gcBrXJE.svg
  dist/assets/backgroundShin-CcjkscEZ.svg
  dist/assets/baek_mentorChatBubble-DijFPC_6.svg
  dist/assets/fromBaek-DT0BLmko.svg
  dist/assets/fromOh-DO2UuJGk.svg
  dist/assets/fromShin-B6bB3TrY.svg
  dist/assets/groupLogo-UiVsXh0O.svg
  dist/assets/index-Cj_By1DR.js
  dist/assets/index-DayvVuVL.css
  dist/assets/index-kRV1aGTp.js
  dist/assets/mobile_prescriptionimg-C3exaAV2.svg
  dist/assets/oh-BzLDIxT2.svg
  dist/assets/oh_mentorChatBubble-7h2WrPM4.svg
  dist/assets/prescriptionimg-CO1W0rsR.svg
  dist/assets/redButtonBaek-BRTcfWeM.svg
  dist/assets/redButtonOh-C7l3dlAU.svg
  dist/assets/redButtonShin-YJdHy-Ah.svg
  dist/assets/shin-Dkk0NJtx.svg
  dist/assets/shin_mentorChatBubble-DWAYkhJ7.svg
  dist/index.html
  src/components/chat/ChatContainer.tsx
Labels: ✨Feat

#122 [Design/#118] 로딩 모달, 404페이지 퍼블리싱
  src/App.tsx
  src/assets/images/404.svg
  src/assets/images/loading.png
  src/assets/images/mud.jpg
  src/components/FirstPage/LoginPage.tsx
  src/components/LoadingModal.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
  src/pages/NotFoundPage.tsx
Labels: 🎨Design

#124 [Feat/#114] 채팅 페이지 로딩 애니메이션
  src/LoadingAnimationTest.tsx
  src/components/chat/ChatContainer.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
Labels: 🎨Design

#126 [fix/#125] 첫페이지 오류 및 디자인 수정
  src/LoadingAnimationTest.tsx
  src/components/FirstPage/LoginPage.tsx
  src/components/LoadingModal.tsx
  src/index.css
Labels: ❤️‍🔥BugFix

#128 [fix/#127] 콘솔 오류 수정
  dist/index.html
  index.html
  src/components/FirstPage/Input.tsx
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/ChattingPage/ChattingPage_Oh.tsx
  src/pages/ChattingPage/ChattingPage_Shin.tsx
Labels: ❤️‍🔥BugFix

#131 [Design/#129] 마우스 커서, 파비콘
  dist/index.html
  index.html
  leaf_favicon.ico
  src/App.tsx
  src/assets/images/CardBaek.svg
  src/assets/images/mousePointer.svg
  src/components/CustomCursor.tsx
  src/components/FirstPage/Button.tsx
  src/components/FirstPage/LoginPage.tsx
  src/components/FirstPage/StartButton.tsx
  src/components/chat/ChatInput.tsx
  src/index.css
  src/pages/ChattingPage/ChattingPage_Baek.tsx
  src/pages/MentorPage.tsx
  src/pages/MyPage.tsx
  src/pages/PrescriptionPage.tsx
Labels: 🎨Design
